# Generated by Django 3.2.9 on 2021-12-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_new_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_paths',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
