# Generated by Django 3.2.9 on 2021-12-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_img_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_paths',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
