# Generated by Django 3.2.9 on 2021-11-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_book_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsandcraft',
            name='isbn',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
