# Generated by Django 3.2.9 on 2021-11-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211119_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_depository_stars',
            new_name='rating',
        ),
    ]
